### Persistence time analysis

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import tensorflow as tf
from scipy.stats import norm
from scipy import stats
import json

In [56]:
"""
def filter_data(data_in, max_step_size, window, restriction=10000):
    
    Only keeps data for tracks that are long enough for hurst exponent estimation at a given downsampling step size.
    Args: 
        data_in: pandas dataframe, original data
        max_step_size: int, maximum downsampling step size
        window: int, size of rolling window for hurst component estimation
    Returns:
        filtered_data: pandas dataframe
    
    tracks_to_keep = data_in.TrackID.value_counts().loc[lambda x: (x//max_step_size) > (window+1)].reset_index()['index']
    print(tracks_to_keep)
    if restriction<len(tracks_to_keep):
        filtered_data = data_in[data_in['TrackID'].isin(tracks_to_keep[:restriction])]
    else:
        filtered_data = data_in[data_in['TrackID'].isin(tracks_to_keep)]
    return filtered_data
"""
def filter_data_new(data_in, restriction=10000):
    """
    Only keeps data for tracks that are long enough for hurst exponent estimation at a given downsampling step size.
    Args: 
        data_in: pandas dataframe, original data
        max_step_size: int, maximum downsampling step size
        window: int, size of rolling window for hurst component estimation
    Returns:
        filtered_data: pandas dataframe
    """
    print(data_in)
    tracks_to_keep = data_in.TrackID.value_counts().loc[lambda x: x>2].reset_index()['index']

    if restriction<len(tracks_to_keep):
        filtered_data = data_in[data_in['TrackID'].isin(tracks_to_keep[:restriction])]
    else:
        filtered_data = data_in[data_in['TrackID'].isin(tracks_to_keep)]
        
    print(filtered_data)
    return filtered_data

def downsample(data_input, down_int, start_index=0):
    
    data_out = data_input.iloc[start_index::down_int]
    return data_out



In [57]:
def get_mod(v):
    
    return np.sqrt(v.dot(v))

def get_step_vector(index,data_x,data_y,data_z):
    
    dx = data_x[index]-data_x[index-1]
    dy = data_y[index]-data_y[index-1]
    dz = data_z[index]-data_z[index-1]
    
    step_vector = np.array([dx,dy,dz])   

    return step_vector  

def get_cos_theta(data_in):
    
    track_id_values = np.unique(data['TrackID'])
    cos_theta_avg = []
    
    for tid in track_id_values:
        print('track_id ={}'.format(tid))
        track_data = data[data['TrackID']==tid]
        x = track_data['Position X'].values
        y = track_data['Position Y'].values
        z = track_data['Position Z'].values
        
        length = len(track_data)
        #print(length)
        step_vectors = np.empty((length-1,3))
        cos_theta_temp = np.empty(length-2)
        for i in np.arange(length):
            if i>=1:
                
                step_vectors[i-1] = get_step_vector(i,x,y,z)
            if i>=2:
                
                v0 = step_vectors[i-2]
                v1 = step_vectors[i-1]
                cos_theta_temp[i-2] = np.dot(v0,v1)/(get_mod(v1)*get_mod(v0))

        if cos_theta_temp.size != 0:
            cos_theta_avg.append(np.nanmean(cos_theta_temp))
            print(cos_theta_temp)
        
    return cos_theta_avg

def dsample_get_cos_theta(data_in, ds_rate):
    """
    Args:
        data_in: pandas dataframe
        ds_rate: int, downsampling step size
    Returns:
        h_arr: 2D np array
    """

    for i in np.arange(ds_rate):
        
        downsampled_data = downsample(data_in, ds_rate, i)

        cos_theta_avgs = get_cos_theta(downsampled_data)
        #print(len(cos_theta_avgs))
            
        if i == 0:
            cos_theta_arr = cos_theta_avgs#,dtype=object)
        else:
            
            if len(cos_theta_avgs)>np.shape(cos_theta_arr)[0]:
                cos_theta_avgs=cos_theta_avgs[:-1]
            
            cos_theta_arr.append(cos_theta_avgs)
        
    return cos_theta_arr

def get_cos_theta_dict(filtered_data, step_sizes):
    """
    """
    cos_theta_dict = {}
    
    for i, s in enumerate(step_sizes):
        print('step_size ={}'.format(s))
        cos_theta_arr = dsample_get_cos_theta(filtered_data, s)
        cos_theta_dict["{}".format(s)] = cos_theta_arr
        
    return cos_theta_dict

def save_cos_theta_data(cos_theta_data, file_name):#, window, step_sizes, restriction):
    """
    """
    #with open('cos_theta_dict_'+'w{}_'.format(window)+'s{}_'.format(max(step_sizes))+'r{}_'.format(restriction)+file_name, 'w')
    with open('cos_theta_dict_'+file_name, 'w') as file:
        file.write(json.dumps(cos_theta_data))
      

In [58]:
filenames = np.array(['Control_frame001-200',
                      'Control_frame200-400',
                      'Control_frame400-600',
                      'Control_frame600-800',
                      'Control_frame800-1000',
                      'Control_frame1000-1200',
                      'LanB1_frame001-200',
                      'LanB1_frame200-400',
                      'LanB1_frame400-600',
                      'LanB1_frame600-800',
                      'LanB1_frame800-1000',
                      'LanB1_frame1000-1200',
                      'defLanB1_300817_frame200-400',
                      'defLanB1_300817_frame400-600'])

In [59]:
step_sizes = [1,2,3,4,5,6,7,8]
restriction = 5
window = 20

# iterate over data files and save H dictionary 
for i, file in enumerate(filenames[6:8]):
    print('opened file {}'.format(file))
    data = pd.read_csv('haemocyte_tracking_data/' + file + '.csv')
    filtered_data = filter_data_new(data,restriction)
    cos_theta_dict = get_cos_theta_dict(filtered_data, step_sizes)
    #print(cos_theta_dict)
    save_cos_theta_data(cos_theta_dict, file)

opened file LanB1_frame001-200
       Position X  Position Y  Position Z Unit  Time     TrackID      ID  \
0        121.4970     78.6212     10.6246   um     1  1000000000       0   
1        138.9500    153.3250     10.7094   um     1  1000000001       1   
2         67.7117    259.5530      0.5000   um     1  1000000002       2   
3         64.3338    304.3020      0.5000   um     1  1000000003       3   
4        152.6940    330.2540      0.5000   um     1  1000000004       4   
...           ...         ...         ...  ...   ...         ...     ...   
88585     96.3207    409.5130     70.5000   um   200  1000167233  175630   
88586     77.0704    414.9130     70.5000   um   200  1000175195  175631   
88587     96.6054    422.3520     70.5000   um   200  1000165370  175632   
88588    116.9660    426.8750     70.5000   um   200  1000166302  175633   
88589    112.2810    434.8530     70.5000   um   200  1000169602  175634   

       Absolute Time Unit.1  
0                0.0      

[-0.99475464 -0.92167941  0.99919421  0.82178796  0.91664798  0.25913092
  0.04274055 -0.11077601 -0.4349073   0.97078047 -0.57334068 -0.99986976
  0.23602702  0.04258278  0.18310408  0.88879597  0.92359577  0.08809554
  0.23038096 -0.97504629 -0.72504647  0.58392862  0.98385752 -0.1274313 ]
track_id =1000000017
[ 0.76597582  0.99943102  0.91555467  0.98980888  0.99911427  0.87445856
 -0.89184011  0.61192854 -0.85496813 -0.19682223  0.06492941  0.67323897
 -0.48694579 -0.999763    0.44516449 -0.50561316 -0.35201524 -0.06771244
 -0.85686353 -0.75600051  0.99123627 -0.99949871 -0.83222833  0.99202111
 -0.92360123 -0.66821962  0.08000658  0.73840348 -0.4891287   0.81390589
  0.33837524  0.24096049  0.86964052  0.58730194  0.87523576  0.4503322
  0.83306041  0.87595525  0.78717153 -0.99320158  0.8193093  -0.3760154
  0.18138645  0.5191082  -0.42357293 -0.96697801 -0.10027882  0.86170749
  0.81020063 -0.30586318 -0.47522874  0.95046877 -0.99996056  0.69696197
 -0.85940402 -0.48634991  0.875

track_id =1000000046
[ 0.66643561  0.7456434  -0.62521736  0.18588415]
track_id =1000000047
[-0.40118838  0.9869352   0.16138914 -0.9331281   0.45571674  0.95594079
  0.43048313  0.55431769 -0.67990083  0.98140852  0.60231138 -0.18657629
  0.25565286  0.29228297  0.68267906 -0.81531043 -0.92485936  0.33090102
  0.46041468  0.9630045  -0.16159167  0.86297439  0.74442566  0.3453634
 -0.3416791   0.95009671 -0.43883489  0.20601227  0.57766162  0.97905744
 -0.60240924 -0.21686582  0.06447692  0.31819657 -0.43602158  0.733449
  0.53585492  0.52774121  0.77653236 -0.81139545 -0.66810828 -0.92728519
  0.98923632  0.41701885  0.62105134  0.13579472  0.73790442 -0.43269388
  0.18625975  0.23904     0.83877768  0.72512877  0.508676    0.4303077 ]
track_id =1000000048
[ 0.60050383  0.27074077  0.34587316  0.65887535  0.97881552  0.4742108
  0.28552205 -0.70539342 -0.84275554  0.23646719 -0.16358963 -0.29959376
  0.95359851  0.65100845 -0.14875921  0.97727237 -0.10997983  0.33888782
  0.4164832   

[ 0.76180028 -0.54329801 -0.96442888 -0.92645619]
track_id =1000000068
[-0.93710622  0.34334765  0.16296455  0.84014101  0.9040525   0.70852747
  0.83053491  0.12128842  0.04061322 -0.81969652  0.14343213]
track_id =1000000069
[ 0.08317656 -0.83928456]
track_id =1000000070
[ 0.36226797 -0.39267784  0.69302151 -0.60802575 -0.93541753  0.10388684
  0.2109955   0.64468685  0.35801453  0.29062708 -0.62590475  0.32628164
  0.40245201  0.54917454 -0.86715106 -0.34619607  0.25197407 -0.97449099
  0.90662099]
track_id =1000000071
[ 0.371641   -0.21721299  0.85249756  0.52347406  0.85947304  0.51908385
  0.72160779  0.99299347  0.81088352]
track_id =1000000072
[0.6046485  0.76034869]
track_id =1000000073
[ 0.08616984  0.91828912  0.12672284  0.33999162 -0.82925356  0.29150013]
track_id =1000000074
[ 0.34216449  0.96626074 -0.18907086  0.45476022 -0.59409008]
track_id =1000000075
[ 0.94511122  0.36345279  0.89490695  0.67790057  0.59544777  0.93699143
 -0.90822016 -0.5181927  -0.39472946 -0.7156

[-0.79557173  0.68328305 -0.02141043  0.26933156  0.9669807  -0.12709973
  0.60602028  0.25528793  0.82619794  0.12140755  0.90551305  0.96153012
  0.04769819  0.29477124  0.66745442  0.89276558  0.81419567  0.99610818
 -0.52243502  0.87790727 -0.73373257 -0.66116177  0.05276895  0.75772035
  0.43397057 -0.07770903  0.93438701  0.56542887  0.93995556 -0.03658301
  0.74716394  0.66551357 -0.08844983  0.10413819  0.90903013  0.9767243
  0.85106842  0.99238248 -0.41236282 -0.48724376  0.7078204   0.69897972
  0.87079567 -0.41003143 -0.40437544  0.98862844  0.58507395  0.43893052
  0.84871198 -0.40543911  0.5506904  -0.62594486  0.26975953 -0.3412842
  0.72671976 -0.0212213   0.6203025   0.74746601  0.96600912 -0.17483235
  0.8125738  -0.30918009  0.99365945 -0.75965113 -0.89876938 -0.5830819
  0.68870788 -0.89222791 -0.23258728  0.5638393  -0.43088481 -0.05034152
  0.62783941  0.77546223 -0.24280081  0.86858201  0.13907875 -0.36909496
 -0.85970558 -0.0666759   0.53045476 -0.91270623 -0.47

[ 0.71963399  0.09443332 -0.95358514  0.59599664 -0.4832994   0.08959079
  0.40559905 -0.05768987  0.97926271 -0.43653313  0.05870144 -0.32309209
  0.74610965  0.058106   -0.74618894  0.69459321 -0.28167914 -0.24074031
  0.23579901  0.43323613  0.35059211  0.8176667   0.28513824  0.77194663
  0.19041998 -0.06521617  0.21402397  0.41251847  0.7111461   0.77165936
  0.76313383  0.41757847  0.23768264  0.8786927   0.88159687 -0.38401504
  0.90462587 -0.13253031 -0.50824634 -0.97648669 -0.97030312  0.90746267
 -0.34956952  0.92830889  0.66152139  0.90787004 -0.55482942  0.87409544
  0.22586643  0.72173616  0.67536721 -0.41881594  0.06682426  0.81393887
  0.10777801  0.24173013  0.31754891  0.85418973 -0.13835586  0.00349236
  0.79382712  0.94618259  0.79349369  0.66270533  0.84992201  0.5394313
  0.73551709  0.88193449  0.92885986 -0.49464347 -0.53053029 -0.66419486
 -0.84788715  0.94156154  0.93202192  0.58848836  0.99161053  0.42127866
  0.32334029  0.51031385 -0.55521032 -0.51088396  0.

[ 0.31627452 -0.20054967  0.09344787 -0.40765568  0.96608489  0.34281724
  0.73348514  0.46349513 -0.25822777  0.90116805]
track_id =1000000145
[-0.90357859  0.5129311  -0.99944503 -0.43431547  0.98434824  0.42366233
  0.29543004 -0.37911629  0.65190385  0.9446187  -0.6096031  -0.83498055
 -0.3470599  -0.30583668 -0.72977595 -0.37322561  0.09134691 -0.7468099
 -0.78446852 -0.03694217  0.50627171]
track_id =1000000146
track_id =1000000147
[-0.91630023 -0.19047519  0.92455753  0.47267797  0.609171    0.18720983
 -0.47958858  0.98204569 -0.04424188 -0.18454006 -0.89273232 -0.84538809
  0.95544832  0.96633958 -0.79488366 -0.08265739]
track_id =1000000148
[ 0.43217599  0.69870482  0.9752083   0.80075057  0.995136   -0.98105417
  0.62954551  0.09171464 -0.41805693 -0.73245847 -0.97324547  0.30422439
  0.59277106  0.81967799  0.38518337 -0.95010481  0.75403399 -0.51623017
 -0.76414176 -0.24060533 -0.7101001  -0.45521903 -0.84692013 -0.40325479
  0.24718703  0.32327814  0.44553129  0.9043685  

[ 0.40527166  0.84719531  0.43499533  0.59176201  0.29372043  0.42614099
 -0.16330312  0.47645453  0.67887437  0.47629829  0.55910487  0.86822637
  0.38195611  0.68841355  0.44477164  0.87406395  0.20606651 -0.73527403]
track_id =1000000174
[-0.34522886  0.58868716  0.40751725  0.35810211  0.84923898 -0.38799328
  0.02513574 -0.02129366]
track_id =1000000175
[ 6.61508329e-01  5.87073846e-01  3.51369168e-04 -6.86487519e-01
  7.07519915e-01  2.20025595e-01  6.84060980e-01]
track_id =1000000176
[-7.23750924e-01  9.62386742e-02 -1.73547581e-01  7.49343226e-01
 -6.44977425e-01  5.02346111e-01  8.23768191e-01 -7.05593896e-01
 -7.50922509e-01  1.41651740e-01 -5.75209573e-01  9.61701531e-01
  8.79978131e-01 -9.47745751e-01  6.45025534e-01 -5.40330602e-01
 -2.86762268e-01  8.67094106e-01 -3.25571849e-01  5.98502172e-01
  7.63864810e-01  9.99810675e-01  4.23299443e-01 -3.87425801e-01
 -1.68831440e-01  7.81646085e-01 -3.07983156e-01  9.48793133e-01
  6.39704713e-01  5.15383340e-01  2.42824557e-01

[ 0.51468481 -0.38187581  0.9881661  -0.49046131 -0.32397736 -0.57568028
  0.79787683  0.54690137]
track_id =1000000200
[ 0.32851342 -0.22109346  0.81299274  0.66276462  0.54673826 -0.73941124
  0.82501283  0.25559485  0.51418738  0.54413299  0.82160107 -0.84854197
 -0.02490902 -0.24848558  0.74492193  0.84691984 -0.8087457   0.296303
 -0.08454692 -0.19452262 -0.0408009   0.14087665  0.69989938 -0.99205096
  0.84294455]
track_id =1000000201
[-0.86581263  0.38418408  0.76409175 -0.47830653  0.81326114  0.74012853
  0.9980852   0.88691251 -0.94438583 -0.29014917  0.22625807  0.65387979
 -0.42905304 -0.78489228 -0.39819915 -0.26809012  0.00983129 -0.64002299
 -0.46174582  0.33425255 -0.56631787  0.98568291 -0.19061622  0.38091283
  0.8081775  -0.8428263   0.43265389  0.57988904 -0.82351861  0.8700522
 -0.56364352  0.86399265 -0.11584519  0.29694785 -0.493082    0.98634884
  0.34190756  0.62368905  0.51576635 -0.57802262  0.95849729  0.63837882
  0.75689845  0.5980709   0.92659198 -0.30265

[ 0.90406233  0.92634795 -0.5694808  -0.88461915  0.17836882]
track_id =1000000225
[-0.01685754  0.57759291  0.3681757   0.65177976 -0.32400516 -0.19603175
 -0.87934653 -0.52035727  0.87078578 -0.89376879  0.73501696  0.90778443
  0.83292648  0.50702068 -0.77269724  0.81942584  0.54746103 -0.57852808
  0.03095508 -0.46957858  0.93057329  0.99990473 -0.24910639  0.89111984
  0.89981848  0.96985948 -0.6509969   0.53932397 -0.16698397  0.62713841
  0.47403323 -0.93434295 -0.8184594   0.05873007  0.94098722  0.59948273
  0.04222159  0.77626711  0.88089493  0.9762467   0.96324448  0.31323684
 -0.48831908  0.43809444  0.82487405  0.99552261  0.97272558 -0.71798096
  0.53580562  0.0564033   0.79451826 -0.03526091 -0.33564464  0.59259907
  0.95185019  0.98646613  0.70618777  0.86284882  0.41570849  0.72971395
 -0.97555376 -0.64961299 -0.42662914  0.21128815]
track_id =1000000226
[ 0.49312746  0.92786786 -0.36834162  0.74761897 -0.50176115  0.95222752]
track_id =1000000227
[ 0.89549851  0.16651

[-0.67341353 -0.02505637  0.14111254 -0.92052971 -0.932809   -0.73221493
 -0.43227505 -0.85233616 -0.17814719 -0.92755325 -0.96280379 -0.98529109
 -0.99310089  0.83840337  0.48648185  0.9947683  -0.84452203 -0.28969076
 -0.05429341  0.93803314  0.74255486  0.16888419 -0.51650676  0.14439356
 -0.4772915  -0.84980277  0.88895303 -0.95899717 -0.87399468 -0.9470177
 -0.52031039 -0.57993504]
track_id =1000000248
[-0.54635369 -0.86711722 -0.98575027 -0.80627949 -0.6586676   0.08934175
  0.65407274  0.66884634  0.25827316  0.91247257  0.30175834  0.88684157
  0.8045607   0.94923202 -0.10058443  0.54234927  0.40073479 -0.92175538
  0.39460474  0.94414317  0.74163038  0.98008702  0.56635805 -0.82094484
  0.70785535  0.14847323  0.53892524  0.67788497]
track_id =1000000249
[ 0.67795849 -0.45338939  0.6598094   0.25052177 -0.63987091  0.32097815
  0.65664253 -0.61816369 -0.93531215 -0.86620934  0.66548008  0.34657134
 -0.23962589  0.68505423 -0.15260794  0.04881126 -0.75054065 -0.05613778
 -0.889

[0.71343454 0.10913016 0.62100583 0.5275391  0.22209696 0.97172364
 0.50985069 0.71600268]
track_id =1000000276
[-0.25890006  0.79604035  0.17321464  0.67576627 -0.86550574 -0.88624852
 -0.74074084 -0.57080167 -0.32568239  0.32858454  0.59356604 -0.50112703
  0.04167019]
track_id =1000000277
[-0.10429229  0.22061772 -0.98009522 -0.32844144  0.11138621 -0.22278307
  0.54422935 -0.16510337 -0.74754701  0.30885435  0.65477321  0.6199933
  0.84904763 -0.87329861  0.11136725  0.47430327 -0.49365721 -0.18984718
 -0.56013305  0.48788834  0.87099048 -0.772418   -0.07877861  0.31357626
  0.4973604   0.19617279  0.51067666  0.13130245  0.88314605 -0.83530652
 -0.78422987  0.5085173   0.82990175  0.38817203 -0.46243644 -0.5315893
  0.35806942 -0.08198932 -0.04018807 -0.63635563  0.85506177 -0.39670443
  0.23637286  0.49190479 -0.58818786  0.70520246 -0.05986618 -0.07897368
  0.1157167   0.83469693  0.14237964 -0.18276503  0.99652536  0.89716104
  0.75810738 -0.68708143 -0.56095973  0.14175553 -0.

[-0.50647536  0.8534549   0.62682419  0.97446659  0.18338104 -0.44401063
  0.77145058  0.82620073  0.56606703  0.02053234 -0.24352008  0.49335276
 -0.95119735]
track_id =1000000302
[ 0.55975946  0.2119644  -0.66883502 -0.30802398 -0.23246253 -0.11754859
 -0.50596042  0.76355903  0.95236294  0.77024929  0.62871221  0.67974908
  0.89347656  0.23064295  0.38647595  0.04648212 -0.68858385 -0.42332877
  0.20415457  0.87383197 -0.81552897  0.95454142 -0.99435504 -0.96926823
 -0.72851039  0.1372996   0.77245176 -0.51730202 -0.28368944 -0.43108486
  0.21374091 -0.43293732 -0.24060421  0.87576357  0.84958862  0.61718084
 -0.32412866  0.75110622 -0.67416332  0.42019131 -0.03865762  0.49397665
  0.36891522  0.28883778 -0.59050616 -0.04107547 -0.35162764 -0.93261419
  0.35207833 -0.38230677 -0.82995601  0.36275951 -0.693396   -0.6687721
 -0.96884778 -0.33924896  0.86269013  0.33202478 -0.17153578  0.67301017
  0.96426759  0.47059526  0.55574518  0.61570077  0.27905258 -0.4608267
  0.63679065 -0.15

track_id =1000000321
[-0.88607839  0.86053862  0.69039713 -0.90500731  0.94552247  0.82750172
  0.99556608 -0.32841816  0.32575605 -0.59076003 -0.75526009 -0.7030565
 -0.47604438 -0.95264733  0.95567227  0.8743673  -0.84241929 -0.95492803
  0.59353877 -0.71995046 -0.97466049  0.99567022  0.39220621 -0.04708447
 -0.8810965  -0.60597946 -0.41315446 -0.14252744 -0.74051552 -0.48863091
  0.73812771 -0.96104863  0.87734528 -0.19199968  0.18496415 -0.86483966
 -0.95502815  0.87379408 -0.73276136 -0.30494421  0.29294563  0.67934877
  0.20274325  0.25015204  0.73353624 -0.30423474 -0.21447539 -0.92999584
 -0.81918895  0.44467715  0.30914838 -0.08986586 -0.43176545  0.15886237
 -0.67637327 -0.37541197  0.34542482 -0.4696765  -0.23465081  0.88101447
  0.99801484 -0.86460789 -0.81527056 -0.7421362   0.85440493 -0.55337602
  0.93424049  0.41253286 -0.70541978 -0.2908171  -0.25597059 -0.58021854
  0.38287796  0.5926821  -0.21986384 -0.20484678  0.61423743  0.94912119
  0.79906171 -0.26115247  0.881

[-0.62053049  0.7754822 ]
track_id =1000000343
[ 0.97297781  0.29702502  0.04783892  0.65307677  0.68132747  0.3844627
 -0.80249672 -0.60326404  0.7557639  -0.05900772 -0.37176284  0.07957419
  0.19608227  0.42897     0.88024857 -0.54369061 -0.00714385 -0.7136925
  0.62489181  0.44888881  0.91284901  0.26166647 -0.54683382  0.80911875
 -0.12294872 -0.64366737  0.78373677  0.64251815  0.64767087  0.54617778
  0.48737411  0.83786941  0.57350742  0.46177524  0.08388591 -0.52121488
 -0.30271585  0.44337681  0.74997982  0.25222206 -0.49820291 -0.78313406
 -0.78267956 -0.0958086  -0.12920061  0.62083755 -0.57522824  0.52947182
  0.75247421  0.81107062 -0.55757899 -0.63583751 -0.11209972  0.40624538
 -0.78508947 -0.44527754 -0.02385237  0.65247697  0.45536428 -0.80525633
  0.9320707   0.72905364  0.34643734  0.96380224  0.8571537   0.37793212
 -0.10169501 -0.9966223   0.92848575  0.55929496  0.87521492 -0.97392161
 -0.51477551  0.03972436 -0.11807378  0.07573333  0.91608682  0.37772604
 -0.18

[ 0.26504509 -0.50656151  0.0288485 ]
track_id =1000000423
[-0.97648841  0.52283768  0.674382   -0.58850106 -0.61505937  0.38476506
  0.4499255   0.92028813  0.16701576  0.75803204 -0.18137793 -0.79493574
  0.13366165  0.36860587 -0.72956636  0.72263357 -0.3344591  -0.46915156
  0.41322324 -0.31744545  0.56923104]
track_id =1000000427
[-0.87209241  0.73643629  0.96086734 -0.71617751  0.33672087 -0.28709811
  0.95385669 -0.95085934 -0.54660643  0.77264371  0.2865472   0.42566832
  0.99726433  0.89524309 -0.69900824  0.67443965  0.92550114  0.09960808
  0.98709    -0.57143054  0.98824421  0.91003277  0.75002949 -0.87594514
 -0.76992389 -0.80916363 -0.57136123  0.99830194  0.45093126  0.30183777
  0.73882204  0.59825964  0.42656694  0.1403021   0.25043739  0.79453012
  0.08211022  0.28567511  0.76072652  0.14055062  0.06610399 -0.26347328
  0.31937751  0.72529601]
track_id =1000000434
[ 0.99824827 -0.06797771  0.50488857  0.50020611  0.95640277 -0.79733307
 -0.70915516  0.78411262  0.1334

[ 0.88264308 -0.71766399]
track_id =1000088669
[0.17771679 0.06126397]
track_id =1000088692
[ 0.88150628 -0.9576776 ]
track_id =1000088694
[-0.32806002 -0.49892754 -0.83862831 -0.81739388 -0.31577379 -0.6346547 ]
track_id =1000088696
[ 0.84138426  0.89798711  0.471969    0.27447899  0.80887489  0.79823951
  0.20640539  0.87728587  0.86775573  0.74990864  0.9251993  -0.72800997
  0.54902095  0.58965416 -0.34456801  0.94590438  0.46542858  0.20614187
  0.87100739 -0.61934116  0.16898552  0.12450366  0.19713372  0.79814746
  0.82851789 -0.86732592 -0.35387783  0.65713021 -0.29121083 -0.46894262
 -0.20485245  0.94729462 -0.63155535]
track_id =1000088700
[0.09582939 0.47133847 0.29022453]
track_id =1000088706
track_id =1000088750
track_id =1000088814
[ 0.23713508 -0.27507202]
track_id =1000088860
[-0.07291533 -0.21979913  0.82845324  0.47927087 -0.9471248   0.87646865
 -0.97255453 -0.99636734  0.43192973 -0.12275047  0.35019014 -0.58805069
  0.64393556 -0.51483354  0.86329242  0.78480609 -0

[ 0.67877912  0.75086319  0.82752318 -0.90962375  0.83388516  0.28188039
  0.20399569  0.43057042  0.61654687  0.88296112 -0.95571874  0.51067211
  0.48396383 -0.67149715  0.38354369  0.52396826  0.50977211 -0.51874874
 -0.934477  ]
track_id =1000089197
[-0.00302329 -0.24594113  0.94057208  0.86081825  0.20318186  0.80822128
 -0.02881853 -0.93556557 -0.47620772  0.33350183  0.4522501   0.37617389
 -0.32495363  0.83679938 -0.28790159 -0.24917761 -0.5320333   0.72722611
  0.6172147  -0.99492734  0.04470674  0.08030214 -0.89854003  0.23597074
  0.30915543  0.31620785  0.17778127  0.88085001]
track_id =1000089202
[0.11006465 0.52881542 0.04842235]
track_id =1000089222
[-0.54085233  0.56007604  0.64504897  0.66900273  0.38223546 -0.32571248
 -0.25117614  0.50415497  0.6356276   0.43751781 -0.59483838  0.65127627
 -0.37949537  0.08542521 -0.20200207  0.58566199 -0.64265599 -0.80003227
  0.42998328  0.74514855 -0.13695488  0.94589256 -0.2761879  -0.21206839
 -0.56106992 -0.93191641  0.2812883

track_id =1000090376
track_id =1000090377
[ 0.86513512 -0.26123284 -0.61523195 -0.79651373 -0.83331628 -0.1573918
 -0.89079401 -0.96516153 -0.90115991  0.71857062 -0.55441074  0.98746909
  0.20558078 -0.48312305  0.78469319 -0.98204256  0.83868828 -0.50328975
 -0.79469951  0.92016388  0.21012213 -0.13697587 -0.66477824  0.38156332
 -0.62906716  0.17891305  0.76775935 -0.03759263 -0.49181905  0.91407527
 -0.81904609 -0.40433673 -0.24061576  0.26683477  0.8501886   0.95861914
  0.73790631  0.62585388 -0.75980161 -0.30958558  0.56552108  0.68837887
 -0.5503634   0.70293677  0.92452045  0.9163184   0.71567722  0.98993875
 -0.57075715 -0.03242556 -0.71843081 -0.20541314 -0.57556279  0.93874823
  0.14505562  0.82173252 -0.8555814   0.78129664  0.90042439]
track_id =1000090379
[ 0.66352132  0.98709091  0.8559938  -0.85857984 -0.19982528  0.91332836
 -0.25098045]
track_id =1000090389
[0.59250422]
track_id =1000090434
[ 0.7555087  -0.04652039  0.88764918 -0.94942777  0.5478611   0.14619404]
tra

[ 0.87251051  0.98665568  0.99425945  0.63217483  0.82633675  0.66777063
  0.94911119  0.87918856  0.42698235  0.92110154  0.95711032 -0.70107929
  0.74743039  0.46516565  0.23303688  0.90197002]
track_id =1000091787
[0.7907138  0.33297941]
track_id =1000091790
[ 0.24082948 -0.79276471  0.78439062 -0.52735913 -0.91743417 -0.00939612
  0.02265162  0.87469247 -0.85760526  0.32332345 -0.97121432  0.58149699
  0.96802567 -0.92840881  0.95467662  0.84883538 -0.08265954 -0.98706034
 -0.914248    0.67214589  0.92619822  0.72310153  0.95605041 -0.84535306
  0.79981076  0.48608012 -0.99667224 -0.30602587 -0.91888286]
track_id =1000091792
[-0.97931855  0.86690704  0.28463201 -0.99988095 -0.85989624  0.87319317
 -0.62833869 -0.67220798 -0.96741973 -0.99997758 -0.99046759  0.45148048
  0.08370078 -0.93984425 -0.99657482 -0.42277659 -0.93728927  0.80860599
  0.99886663 -0.86187482  0.85762107 -0.50935379  0.92481565 -0.48673836
 -0.98820147  0.1989849   0.33283609  0.50984387  0.57296823 -0.8848198

[-0.85989973  0.94431697  0.71891304  0.45368387  0.84262516  0.76097427
 -0.82025249 -0.59768137  0.03242101  0.87221784  0.57184457 -0.47846829
  0.84375066  0.8151529   0.58958367  0.93868273  0.7152533 ]
track_id =1000093073
[ 0.83415667  0.26960717  0.82482826  0.62626812  0.7930304   0.60072988
  0.18674721  0.89148582 -0.99361525]
track_id =1000093089
[-0.81690183  0.61711664 -0.90718885 -0.74016507  0.01437587 -0.74034911
  0.8965307   0.46962872 -0.76091294  0.07450146  0.75410394 -0.19906078
  0.29073495 -0.1806853  -0.97027028 -0.78263614  0.44654681  0.07343067
 -0.06350727  0.3310658  -0.17834041  0.09109072  0.97056528 -0.54272162
  0.62898096  0.82461009 -0.76841081 -0.98467091  0.51084549  0.91068995
  0.31889336 -0.3464882   0.89519342  0.47051561  0.78509367  0.7613331
  0.78543887 -0.90617197 -0.90643466 -0.31819364  0.62729235  0.67977098
  0.16811776 -0.77789856 -0.6038544   0.20112296 -0.90350053 -0.98281784
  0.55784942  0.48759208 -0.02827965  0.46074273  0.8990

[-0.72190671]
track_id =1000094459
track_id =1000094469
[0.97252314 0.97603619 0.84460064]
track_id =1000094526
track_id =1000094532
[0.07858698 0.21961179 0.97941821 0.6226015  0.61116506 0.90502404
 0.0922549  0.10363924]
track_id =1000094548
[-0.72580417 -0.86747618 -0.95895832  0.32574832  0.75724473  0.97768124
  0.6016616   0.20386423  0.77165787  0.96462272  0.5601277   0.89258599
  0.51330823 -0.14364469 -0.9847745   0.39469785 -0.78001162  0.99955778
 -0.91855816]
track_id =1000094558
[ 0.11359362  0.17727326  0.28273554 -0.98010471  0.37484161 -0.8422102
  0.24547256]
track_id =1000094559
[0.37632369 0.8995454 ]
track_id =1000094562
[ 0.36123336 -0.7688497  -0.07926612  0.60241869 -0.16543196  0.04168247
 -0.82378712]
track_id =1000094581
[ 0.59705995 -0.99369944 -0.13872763 -0.72483502  0.70467343  0.40166338
 -0.18109021]
track_id =1000094597
[ 0.95460246  0.81476459  0.21746646  0.24059972  0.68253221  0.54316792
 -0.77661292  0.20695593  0.58069642]
track_id =1000094600
[

[-0.6780622  0.1940312]
track_id =1000095884
[-0.19532275  0.8460946   0.90469684  0.23333893  0.90909682  0.87045321
  0.76629317]
track_id =1000095890
[ 0.91147676  0.89243317 -0.39039742  0.3010057   0.95238158  0.53230286
  0.96481097  0.31181769  0.86841936 -0.48842687  0.70395237  0.86558408
  0.96672099]
track_id =1000095917
[-0.28273183  0.88760362  0.84673529  0.87553639  0.75569334  0.91263032
  0.17458267  0.71740522]
track_id =1000095934
[ 0.45708397 -0.79953777 -0.06508555  0.36073025  0.19346955 -0.11803472
 -0.00829445]
track_id =1000095953
[ 0.11243791 -0.91845672]
track_id =1000095962
[ 0.21687098  0.94172274  0.41799149  0.52054963 -0.82691682 -0.04027993
 -0.68155941 -0.78452574 -0.62038501 -0.10079142  0.16743006  0.70972492
 -0.90589244  0.6902585  -0.59785781  0.70696126 -0.87767995  0.01610489]
track_id =1000096025
[ 0.94999059 -0.52031614  0.04087585  0.56082454  0.28214479 -0.180072
  0.31490437 -0.19412013 -0.26285052  0.95393411  0.25355669 -0.08297102
  0.15

track_id =1000097427
[ 0.99655178 -0.53256328  0.92796927  0.77782603  0.59842194  0.87116822
  0.97101325  0.79299583  0.33430957  0.5327623   0.12810745  0.7856203
  0.91060012  0.54665262  0.89857807  0.39455944]
track_id =1000097435
[-0.58622685 -0.02698706  0.20948055 -0.31753344  0.15647711  0.34428984
  0.94584539  0.24772394  0.42247004  0.78899806 -0.76901275  0.70188744
  0.47560294  0.84073599  0.93459796  0.6185894   0.1137749   0.33918053
 -0.99378793  0.30878207  0.75639572  0.63740185 -0.96704827  0.49374135
  0.61646415  0.94028253 -0.70987244  0.3040353   0.18642692  0.22527414
  0.39917372  0.5647644   0.79783249  0.7861815   0.10344285  0.98040555
  0.10443472  0.90797696  0.0157231   0.9198043   0.93639333  0.5898983
  0.73984792  0.88380994  0.9751266   0.9835587   0.80538665  0.98065311
  0.93166962  0.79590301  0.53109566  0.93733455  0.06003264  0.64953515
 -0.08446862  0.07405461  0.83151925  0.91392401  0.89786894  0.49681406]
track_id =1000097461
[ 0.95197158

track_id =1000098026
[0.14155433 0.04904432]
track_id =1000098067
[-0.75682574 -0.12968778  0.13002716]
track_id =1000098106
[ 0.71807842 -0.55495229  0.87238966  0.70519715 -0.93484819  0.95840103
 -0.0787361   0.93394145  0.15331099  0.20324524 -0.00968401  0.40977632
 -0.3943635   0.37090067  0.07437703 -0.07585883 -0.74441005 -0.74426246
  0.15747096  0.42445509  0.5656227  -0.77054876 -0.86550561 -0.31427742
  0.3903226 ]
track_id =1000098122
[-0.72034625 -0.99235726 -0.96669988  0.63169597  0.31960377 -0.57946072
  0.9348928  -0.969007    0.92234009  0.24351507]
track_id =1000098200
[ 0.9859831  -0.36897155  0.52818172 -0.87899729 -0.17825258  0.57799437
  0.92517625 -0.08980206 -0.88853255 -0.27926564  0.47256397  0.63935543
 -0.58733059  0.52019701 -0.2332609   0.41772029 -0.16615069  0.63860014
  0.47125138 -0.84157588 -0.1770419  -0.00632931  0.75618581  0.46469354
 -0.83006225 -0.65153596 -0.95509066 -0.26340378  0.93575     0.77454688
  0.57134137 -0.75064534]
track_id =100

[0.79839376]
track_id =1000099189
[ 0.1944616   0.91176675  0.77331442  0.93253853  0.66807214  0.9591473
 -0.01144998  0.83114952 -0.64091403 -0.81379783  0.79047326 -0.34622247
 -0.58305308  0.93861157 -0.14580701  0.87095374  0.4171994 ]
track_id =1000099191
[0.61749095]
track_id =1000099233
[ 0.07383955 -0.68938866  0.11937272  0.91021112 -0.8886614   0.81805721
 -0.25365594  0.16878916]
track_id =1000099272
[ 0.97815901 -0.99971852  0.16927587 -0.26936794  0.25095449  0.89117616
  0.35568782 -0.39922514  0.99346788 -0.73142346  0.9630887  -0.81504409
  0.36175074  0.41144968 -0.01543102  0.80692153  0.17024704  0.29303179
 -0.1832458   0.80942185 -0.83283756 -0.3857795  -0.0154308   0.73604996]
track_id =1000099299
[ 0.99358656  0.78841827 -0.98445437]
track_id =1000099317
[-0.93693698  0.05376246  0.20588356  0.89595915]
track_id =1000099335
[-0.95890887  0.43559819  0.59890779  0.51988386  0.76544637  0.13791843
  0.41065311 -0.11408182  0.71731189  0.97800798  0.36234564  0.607

[ 0.95645971  0.86882703  0.43085474  0.03245567 -0.13468069 -0.33498782
 -0.77145324 -0.63782205 -0.12016705  0.77943312  0.5170285   0.4710286
 -0.87954606  0.90098272  0.06721265  0.67146909 -0.14723348  0.56194016
 -0.63262081 -0.40810647  0.2717684  -0.73984837 -0.845565    0.221549
  0.19726434 -0.46013043]
track_id =1000100694
[0.24347973]
track_id =1000100713
[ 0.18751279 -0.79741187]
track_id =1000100716
track_id =1000100726
[0.79574252 0.07951297]
track_id =1000100746
[-0.3126922  -0.64805734 -0.51457583  0.00712246  0.66821104  0.68083707
  0.28392462 -0.19221506]
track_id =1000100753
[ 0.89451016 -0.91309352 -0.70863511 -0.11487833  0.77861371 -0.69333087
 -0.13846447  0.32960223 -0.98267012  0.62420131  0.26881    -0.80949529
 -0.67072822  0.53206887  0.67598697  0.8349545  -0.64968357  0.90398735
  0.73946137 -0.85827328  0.92261329  0.98181383  0.64535965  0.50720384
  0.62655444 -0.98729669  0.7896546   0.14066352  0.41601069  0.92054098
  0.71733071  0.90696631 -0.4651

track_id =1000101723
[-0.96098962 -0.66274817 -0.24288654 -0.5794236  -0.16758201  0.84604094
 -0.52644607 -0.98267874 -0.92341018 -0.84795423 -0.98455752 -0.82725477
  0.9413394  -0.81948718  0.38030249 -0.88704813  0.78932995  0.47160394
  0.41909567 -0.20935402 -0.07782102  0.26618147 -0.89121921  0.86909909
 -0.96945977 -0.32663894  0.1582421  -0.88820531 -0.66073668  0.89000613]
track_id =1000101726
[ 0.48012719  0.26983319 -0.37694055  0.46192091  0.97387221  0.95343249
  0.81360497  0.82168891  0.95925697  0.28160451  0.56665489  0.4431445
  0.64501065  0.38732111  0.7417014  -0.18210984  0.99276105 -0.17466974
  0.17265962]
track_id =1000101736
[-0.51707686  0.3287532 ]
track_id =1000101784
[-0.99854923  0.71384297 -0.78447582 -0.20591928 -0.02261732 -0.32877166
  0.70717503  0.09853837  0.88517905  0.926866    0.99999645  0.95877663
  0.27909077 -0.9738855  -0.49542678  0.86544543  0.80665056]
track_id =1000101833
[ 0.77990909  0.35679271 -0.71270366 -0.96710746 -0.10072844  0

[ 0.47512423  0.77853165 -0.23980191 -0.31455241  0.0673571   0.30629571
 -0.54452273  0.88557463 -0.27033804 -0.70396449  0.7664954   0.20625688
 -0.43074751 -0.45132576 -0.08291092  0.99627099  0.29715333  0.60494777
 -0.57225868 -0.99505527  0.92135694  0.8266561  -0.88969112 -0.96611834
 -0.99023053 -0.98893128 -0.06972235  0.36500565  0.51193289 -0.75460042
 -0.5370046   0.66637741 -0.72798686  0.94107541  0.25104128  0.58186436
 -0.76370168 -0.08782287  0.42301108 -0.69280812  0.64251699 -0.48018451
  0.69649754 -0.55574112 -0.48830356]
track_id =1000103246
[ 0.06285744 -0.81979873 -0.83073645 -0.46978701  0.59823105 -0.61145995
  0.12101005 -0.04077153 -0.98403635 -0.93789922 -0.24788888 -0.68199503
  0.57600357  0.94104831 -0.29336135  0.2247476   0.06316268  0.21873041
 -0.98184225 -0.29553238  0.60813011  0.77338245  0.38473815  0.23527151
 -0.35979545  0.43306382  0.94840361  0.11521527  0.87398457  0.23546146
  0.74398015  0.7544542   0.64244088  0.11791277 -0.50071039  0.7

[-0.40530235 -0.64195492  0.85417308]
track_id =1000103815
[ 0.69890843 -0.890003   -0.88144901  0.92700761  0.29524922 -0.90775326
 -0.65552682  0.42245567  0.82197814  0.77903445  0.59906243  0.85970439
  0.5004245 ]
track_id =1000103847
[0.84344693 0.91251763 0.5051415  0.94248555 0.02538183 0.55481456
 0.91504588 0.42402117 0.7992926  0.41925378]
track_id =1000103864
[0.08728777]
track_id =1000103881
track_id =1000103902
[0.66344867 0.65118563]
track_id =1000103929
[-0.89912044  0.84681108  0.9189023   0.64355364  0.96707928 -0.16452743]
track_id =1000103945
track_id =1000103955
track_id =1000103959
track_id =1000103961
[ 0.86423197  0.83263454  0.58352117  0.38760154  0.99662878  0.8810613
  0.79968759 -0.28507109 -0.36309065  0.9007327 ]
track_id =1000103984
[ 0.92745228 -0.96210012  0.94673867 -0.22927506  0.02967829 -0.01812673
  0.68013701  0.87841629  0.81168852 -0.39044734  0.04853914 -0.4842497
 -0.40912333  0.1332951  -0.18678394  0.98309219  0.81787755  0.73778426
  0.931

[ 0.57017234 -0.79028627  0.3909532   0.47605038  0.09090832 -0.9167435
  0.87973987  0.82348288  0.88690367  0.04344327  0.82638554 -0.14331596
 -0.71584757 -0.89411622  0.7206961   0.29510391  0.97751176  0.74097293
 -0.76167533  0.71008243  0.27477831 -0.59776548 -0.9306346  -0.97476298
  0.52568855 -0.6482847  -0.3844938   0.55342124]
track_id =1000104990
[ 0.75697965  0.54844532  0.37617863  0.88961661  0.86025659 -0.79737737
 -0.38262472  0.99802127  0.89085733 -0.54845054  0.25908483  0.33956191
 -0.11255249  0.59237468 -0.30208081]
track_id =1000104991
[ 0.83063709 -0.08509207  0.62885355  0.80344237  0.66244115  0.22319141
 -0.65803873]
track_id =1000105008
[ 0.69646568  0.55615719  0.93727893 -0.42402229 -0.34042778 -0.57987113
  0.96776304  0.57865504  0.39807625 -0.47663149]
track_id =1000105029
[ 0.56681285  0.95279299  0.68049025 -0.09064442 -0.96909485  0.17891768
  0.39350716 -0.60782763 -0.99088574  0.78583906  0.45091633  0.1140897
  0.89992205  0.87396231 -0.9552656 

track_id =1000106400
[ 0.50459136 -0.43796899 -0.46584997  0.92375085 -0.12231972  0.51317362]
track_id =1000106469
[0.57868327]
track_id =1000106505
[ 0.07592414 -0.41882871  0.8039411  -0.57250431 -0.99111915 -0.86696907
  0.48054722  0.35170364  0.97037217  0.58166523 -0.03035036 -0.27974724
  0.93761964  0.98422382  0.57234081  0.23861243  0.974595    0.76673201
  0.81406723  0.48957445  0.99565287  0.28830394  0.98128745  0.24904498
  0.72983772 -0.11737443  0.59058389  0.99891779  0.95821565  0.99645077
  0.50756545  0.5551378   0.41122885  0.23296934  0.85307328  0.50707107
  0.73976708  0.83255089  0.93173307  0.952001  ]
track_id =1000106509
[ 0.47602315  0.87671814  0.03014542  0.96357904 -0.22454929 -0.62457041
  0.81598863 -0.0176808   0.47514989  0.58772229  0.84190825  0.39129328
  0.82678627  0.94938653  0.4351523 ]
track_id =1000106595
[-0.28412875]
track_id =1000106625
[ 0.29654315 -0.36111004 -0.84264775 -0.56675628  0.73695152  0.31395185
  0.96478258  0.93870977  0.

[0.42172758]
track_id =1000107755
[-0.94640511 -0.99935573 -0.96122588 -0.93370876  0.9308747 ]
track_id =1000107792
[-0.03231507 -0.53378501  0.98984337 -0.41204294  0.71821883  0.74755493]
track_id =1000107831
[ 0.11670142  0.67364561  0.96250919 -0.89113767  0.87625901  0.77616023
 -0.51981094  0.96035895 -0.24361524 -0.36451119 -0.25308637  0.86854206
  0.75611534 -0.68976631  0.47740455  0.62264328 -0.09592622 -0.88004611
  0.64726464 -0.32822119  0.59421425  0.62673247  0.91078783 -0.72715287
 -0.86324826  0.82240826  0.63306655  0.58056022  0.86228192 -0.75583791
  0.34920278  0.30198476  0.26523806  0.11640637  0.85021561  0.14398611
  0.58959405 -0.05014547  0.61928924  0.82953067  0.08033898  0.65255506
  0.45093414  0.72485128  0.92628871  0.91173482 -0.25416858  0.12712499
  0.90940473  0.90635567  0.7480831 ]
track_id =1000107846
[ 0.92392225 -0.65113377  0.53925364]
track_id =1000107878
[0.47357576]
track_id =1000107912
[ 0.5947194   0.98260899 -0.91182982]
track_id =1000

[-0.9586542   0.61173236 -0.58859976  0.25920533  0.2595364   0.23405258
  0.07644066 -0.26817355 -0.82489279  0.77123936 -0.38365102 -0.02348456
  0.87046878  0.72635865 -0.20524197  0.65202146  0.48787348  0.43481024
  0.62102578  0.1891541   0.33557673 -0.52830047 -0.75591178  0.30402319
 -0.48256072  0.40000957  0.63974839  0.81486907  0.68867003  0.95810757
  0.91733515  0.01800857  0.58095945  0.49331756 -0.56220467 -0.95097337
  0.4844      0.35045082 -0.76042378  0.04992568 -0.42338838  0.89611344
  0.7626883 ]
track_id =1000109236
[-0.16355629  0.45238031  0.50025266 -0.67562269  0.39545101  0.59046975
  0.58065078]
track_id =1000109243
[0.69113198 0.5963459  0.90724362 0.94280325 0.87649306 0.9423237
 0.99891672 0.2361954  0.16604137]
track_id =1000109248
[ 0.59362958  0.6337483  -0.6990708  -0.679271  ]
track_id =1000109256
track_id =1000109271
[-0.36502186  0.42406762  0.74313664  0.96646331]
track_id =1000109321
[-0.86852379]
track_id =1000109327
[-0.33037116  0.30789337 -

[ 0.65246307  0.11705809  0.31126607  0.90368207 -0.5341316   0.32576337
  0.61675472  0.55147628  0.13494699  0.25222509]
track_id =1000110431
[-0.67833975  0.69291379]
track_id =1000110446
[ 0.38412095  0.60729187  0.52283657 -0.91847502 -0.37384708  0.59592286
 -0.549479   -0.17021109]
track_id =1000110458
[ 0.86777742  0.95763932  0.30776334 -0.61187064  0.9785344   0.67710066
  0.91679111  0.82207438  0.76437515 -0.76395135  0.42357453 -0.92966943
  0.23644891  0.18377866 -0.53658799]
track_id =1000110461
[ 0.2627981   0.10577002  0.66006471  0.68783411 -0.8233331 ]
track_id =1000110469
[0.95631938 0.96335237 0.90240422 0.54502621 0.93035136 0.51931928
 0.68370049]
track_id =1000110478
[-0.47780696  0.1471136  -0.41083162  0.54938667 -0.33505153  0.31232629
  0.9947664  -0.19651118  0.61285806 -0.83988315 -0.15985128 -0.13504261
 -0.31482968 -0.97050897 -0.30332109  0.97558623  0.6370449  -0.17170434
  0.37955732  0.98385622  0.93971327  0.52297884  0.67879624  0.88663556
 -0.2859

[ 0.32963639  0.50827447  0.26678397 -0.1029689   0.90044902  0.0185604
  0.77798717  0.47106577  0.49728421 -0.101795   -0.88090113  0.9758287
  0.83862547  0.98178593]
track_id =1000111347
[0.97957382 0.98583085 0.19118355 0.55367856]
track_id =1000111354
[-0.113427   -0.64108262 -0.95487715 -0.63590829 -0.76562139  0.93536365
 -0.56506016  0.90777656  0.86114796  0.80925916 -0.12328956  0.54963873]
track_id =1000111383
[-0.90474012  0.77149298  0.14918533 -0.9243134   0.02888755  0.32813893
  0.41428148  0.83468454]
track_id =1000111399
[ 0.99614514  0.24456932  0.07636839  0.70099788  0.50002517 -0.24247583
  0.10003422 -0.40141959 -0.05368642  0.48168196 -0.30675252  0.88944178
  0.34964184 -0.79745081  0.82043217 -0.92629729  0.4092385   0.47834494
  0.3073685   0.65765863 -0.12610032  0.23877427 -0.13341415  0.05707161
 -0.47658339]
track_id =1000111401
[ 0.05230646  0.66989711  0.15431203  0.65254779  0.5027879   0.92200024
 -0.18985958  0.41582007 -0.92375214  0.74054617  0.99

[ 0.42052422  0.53074371  0.29656527 -0.71467913  0.64980681  0.05538994
  0.89537267 -0.10959083 -0.87467505  0.12471202  0.01081844]
track_id =1000111992
[ 0.99408608  0.99030498  0.93104458  0.85639378 -0.94029612 -0.57929605
 -0.17255369 -0.28784145  0.66252297  0.3364401   0.64321047 -0.4038119
  0.40010281  0.97287577  0.97384106  0.99449953  0.34719367 -0.26118445
 -0.09624828 -0.41519539]
track_id =1000111997
[0.8834496]
track_id =1000112049
[-0.81600664  0.94451862 -0.56042557  0.89440226 -0.62765425  0.71493332
 -0.17134407  0.98395844 -0.89638225 -0.94821947]
track_id =1000112078
[-0.99540066 -0.47186748 -0.84851777  0.55440137  0.57745633  0.85316767
 -0.94031346  0.81595371 -0.93830893  0.78218021 -0.07987426  0.70612451
 -0.83649986  0.08199757  0.70728953 -0.82977872  0.79189444  0.93381331
 -0.99999886  0.99397772 -0.45967637 -0.99965811]
track_id =1000112088
[-0.2422161   0.53113725  0.98050013  0.18554641 -0.37888165 -0.89818317
  0.626887   -0.11803796 -0.16864431 -0

[-0.93361399 -0.87343875  0.3284237  -0.21124765 -0.19640955 -0.3856643
 -0.17425856 -0.62488609 -0.847523    0.07968573 -0.61716418 -0.70334348
  0.36569795 -0.80357991  0.82351627  0.68699694 -0.57923575 -0.9465526
 -0.23801366  0.33336883  0.11260789  0.61153443 -0.87378203 -0.86334051
  0.67491224  0.18394323  0.89443111  0.94256074  0.50295002 -0.48853784
  0.9526405   0.28504099  0.98215595  0.78664104  0.50582037  0.55587982
  0.85248226  0.77726561  0.44276572  0.79594591 -0.68645672  0.60092285
  0.78859541  0.97035113 -0.55139868 -0.59747224 -0.3009198   0.4573164
  0.55210142  0.91202142  0.01953906 -0.99999461 -0.31056874 -0.84144094
  0.04222456  0.73608596 -0.64298231 -0.67051823 -0.81782206  0.99325327
  0.79759219  0.0144187   0.99889029  0.79093283 -0.82924725  0.3346786
  0.93471488 -0.72137777 -0.91285948  0.79448951 -0.68584455  0.54689098]
track_id =1000113388
[ 0.8850753  -0.27408204  0.16356544 -0.04722428  0.84380114  0.61705371
  0.4843772   0.96366484  0.62641

[-0.16659364  0.67639247 -0.86030004  0.94822278  0.81008167 -0.37652193
 -0.98347639 -0.21287178 -0.98322954  0.99923659  0.5917097   0.62947199
  0.93528859  0.48621577]
track_id =1000113991
[ 0.67926657 -0.15946933 -0.0277912   0.33488811 -0.08631264  0.35682363
  0.77210712  0.52618504 -0.96793017  0.35866246 -0.42645585 -0.80314763
  0.73367157 -0.37305383  0.52067067 -0.4919729   0.20230356 -0.35490893
  0.23311883]
track_id =1000114020
[0.86173733]
track_id =1000114030
track_id =1000114067
track_id =1000114103
[0.93272949]
track_id =1000114123
[ 0.0729462   0.41611705 -0.46203226 -0.59036848 -0.82701295  0.7383577
  0.33857481  0.68124128 -0.99893262 -0.33401336  0.50218742  0.95608128
  0.85465757  0.90054435  0.40276095  0.63322958 -0.3946645   0.78570595
 -0.1567613  -0.54383966  0.29293757]
track_id =1000114136
[ 0.31836793  0.06230963 -0.50156616  0.27687923  0.36111428 -0.80360455
 -0.83448671 -0.33995552  0.11653892  0.77059606  0.22880529  0.02951733
  0.94534152 -0.8675

[ 0.97566885  0.15637693  0.59361298  0.93140768  0.85081283  0.55419169
 -0.21837148  0.88300599 -0.34441237  0.64094545  0.04170416  0.42937446
  0.54816396]
track_id =1000115271
[0.64637816 0.09540543 0.97776985 0.86394165]
track_id =1000115307
[ 0.91241671  0.17291786  0.73994554 -0.08529562  0.76935098  0.4751467
 -0.27496276  0.3969286  -0.75297436  0.0436166  -0.81193044 -0.398854
  0.23844248 -0.44088019 -0.28925381  0.97113011 -0.58175952  0.88307302
 -0.55439164 -0.04417958  0.05537966 -0.36236464 -0.6826678   0.86020555
  0.71702168 -0.718386   -0.76835166]
track_id =1000115333
[ 0.35590184  0.4858197   0.15296043 -0.71314078 -0.55948156 -0.13526967
  0.83222706  0.44023462 -0.97865252  0.30801234  0.50860445]
track_id =1000115361
[ 0.8344156  -0.17251187  0.88222239 -0.36905918  0.35396832  0.83482541
  0.69396353 -0.74422459 -0.53416714 -0.35951676 -0.58169119]
track_id =1000115381
[-0.17791561  0.83964576  0.24897053 -0.82042013]
track_id =1000115382
[-0.44074904 -0.62291

[ 0.97158064  0.21955141 -0.10048536  0.65774618  0.21728937  0.38803403
 -0.74316143]
track_id =1000116650
[0.30348731 0.39415919]
track_id =1000116655
[ 0.67486832 -0.85241278  0.54378032 -0.88819632  0.33307542  0.62121855
 -0.05256714 -0.27611269 -0.72157474  0.12572998  0.16205122 -0.64583717
  0.5394178   0.70579087]
track_id =1000116658
[-0.85187367 -0.48546888 -0.33448941  0.99376722 -0.27463268 -0.13737638
  0.23585338  0.1680103  -0.33850777  0.47447045 -0.49444151  0.33489034
  0.90350575  0.47802458  0.02062449  0.62658585 -0.28307847 -0.00461442
  0.9541001  -0.31481545  0.97881455 -0.91007058 -0.16146386 -0.66191843
 -0.81001415  0.00907719 -0.73544906  0.68616766  0.97248513 -0.27861998
  0.77321879 -0.54501712]
track_id =1000116674
[ 0.21338956  0.73927835  0.38938564  0.4148278   0.80833648  0.55809188
  0.93088615  0.46482089 -0.52556944  0.90179689  0.49023783 -0.68789552
  0.55945577  0.30177944  0.25149335  0.72469909  0.81324927  0.52159143
  0.64378626 -0.0511259

[-0.95754546  0.49464726 -0.00209597 -0.1082104  -0.17152453  0.87159383
 -0.40695083 -0.04354822  0.79201391  0.55522729  0.20121561 -0.16479755
  0.6767235  -0.53436929  0.43962325]
track_id =1000117964
[ 0.09033673  0.33320312 -0.47340647  0.04988     0.78298397 -0.04275782
 -0.80962553 -0.81708876 -0.77323557  0.98922873  0.0977862   0.70928778
  0.00657252 -0.49516254 -0.62390772  0.92480432  0.3864342   0.55081065
  0.7589972  -0.41196269  0.82777047  0.58164615 -0.85066154]
track_id =1000117982
[-0.13025217 -0.08820077  0.81925179  0.02178477 -0.4429571  -0.289652
  0.10759799  0.93031358  0.75571853  0.83532256  0.31643734 -0.03295499
 -0.86482266  0.74260926  0.48905404  0.49194197  0.59335713  0.537239
  0.5128835   0.21837206 -0.81686722  0.61629266  0.94579256 -0.47475243
  0.29357238  0.62597894  0.97429008  0.54256835  0.43557965  0.67076822
  0.97380734  0.7281919   0.15595254  0.53342611  0.66557441  0.898332
  0.75406623  0.25640468  0.57144604  0.26830854  0.67729265 

[ 0.98844776  0.85690223  0.73329807 -0.53898174 -0.79837614  0.91056098
  0.88638085  0.0865528   0.26058692  0.03007999 -0.69618925]
track_id =1000119109
[-0.99279434  0.43941217]
track_id =1000119140
[-0.30176244]
track_id =1000119176
[-0.21253833 -0.04321764]
track_id =1000119190
[ 0.92018159  0.53773746  0.81272066  0.04993579 -0.34720945 -0.29349694
 -0.57810022 -0.16129157  0.97465936  0.91232108  0.01430825 -0.93866637
  0.84549818  0.00547874  0.36963986  0.43312687  0.55697967 -0.54091446
  0.57210037  0.01190366 -0.7463957   0.37586694  0.50650632  0.98545095
  0.96963453  0.71926481  0.72849847 -0.33707213  0.40823662  0.39865388
 -0.66892815 -0.65006696  0.51570789 -0.19596781 -0.13430931 -0.53569715
  0.21619867  0.79610796  0.60019748  0.01256278  0.24405617  0.56916051
 -0.84126891  0.71666361  0.96306195  0.85493821  0.64194276 -0.86965052
  0.56590485  0.39982929 -0.08447051  0.34810534 -0.98634493  0.41921963
 -0.39263925 -0.39291367  0.16304998  0.74359834  0.670466

[ 0.90433732 -0.34283845]
track_id =1000119864
[0.97293766]
track_id =1000119872
[-0.61039532 -0.39630815 -0.51896619  0.26833883]
track_id =1000119877
[-0.46662223 -0.15028727 -0.24344357  0.097125   -0.2402606   0.75299649
  0.42128766  0.91158553  0.67971629  0.88974468  0.99766588  0.98827778
  0.92422711  0.61556295]
track_id =1000119882
[ 0.82589184 -0.86101354  0.98192339  0.89365558  0.88823693 -0.47677282
 -0.7894042   0.8648752   0.80108533 -0.98272226  0.1271997   0.20357469
  0.60825608]
track_id =1000119885
[-0.28240055  0.4076153   0.01235374  0.21582189 -0.188812    0.71728825]
track_id =1000119893
track_id =1000119900
[ 0.84146792  0.51995708  0.83291134 -0.50781116  0.80123428  0.33823922
  0.87169892  0.25598363  0.98302956 -0.85391467 -0.95610942]
track_id =1000119918
[ 0.74364725  0.75849074 -0.57350719 -0.39388009  0.55665317]
track_id =1000119978
[ 0.82615767  0.65835474 -0.05371626  0.75593995 -0.47770792  0.25607721
  0.71788884 -0.05165591 -0.95285334  0.946225

[ 0.87202208 -0.49989981  0.45748945  0.97554812  0.93026288  0.97147814
  0.9038987   0.95118739  0.15266158  0.96595342  0.1891822   0.21024198
  0.78295233  0.60139542 -0.29505361 -0.19203183]
track_id =1000121139
[-0.4878576]
track_id =1000121148
[ 0.72157203 -0.72407452]
track_id =1000121170
track_id =1000121184
[0.05165069 0.87343107]
track_id =1000121203
[-0.97118642]
track_id =1000121253
[0.7883962]
track_id =1000121257
track_id =1000121262
[ 0.95251478  0.68511274  0.43325009 -0.96485367 -0.14199216  0.91397207
 -0.89278486  0.58052467  0.85478531  0.75926293]
track_id =1000121280
[ 0.3497872   0.30004758 -0.16952616  0.86085218 -0.86911977  0.79710006
  0.68497866  0.21962292  0.93261476  0.25725438 -0.29479061 -0.86963184
 -0.63559345 -0.42521315 -0.73527312  0.70885925  0.46237727 -0.20234344
  0.64591816  0.64122854  0.98983075 -0.47951469  0.98939104  0.80257833
  0.27434287]
track_id =1000121282
[ 0.87471892  0.38275924  0.43733175  0.97860342  0.96707174 -0.40964139
 -0

[0.82787227 0.52727072]
track_id =1000122637
[ 0.99129827  0.12660296 -0.26368016  0.90096964  0.39412513 -0.00194108
  0.52193104  0.90214812 -0.56167539 -0.42887609 -0.63688178  0.54717927
  0.8461861   0.81716151  0.75830659 -0.4375073  -0.0308702   0.98400951
  0.47860645  0.71311131  0.94144036  0.82969245  0.44876002  0.70744852
  0.80145772  0.59887251  0.0238979   0.97442579 -0.37387049  0.89052228
  0.59467117  0.93681278  0.95598663  0.56617289  0.3865347   0.99735538
  0.38662246 -0.01350853  0.92892274  0.96304306  0.9778406   0.94178648
  0.63903678  0.88201173  0.80546163  0.38867689  0.85617629  0.90544686
  0.2000401  -0.13627185 -0.16720519  0.1328145   0.95017081  0.57100663
  0.20471418]
track_id =1000122638
track_id =1000122641
[ 0.97348074  0.29987918  0.36909402  0.73738476 -0.20799621 -0.43141659
 -0.19353996  0.99628889  0.2013153   0.96175331  0.93639054  0.85733033
  0.48578878  0.82003946  0.89087793  0.48848602 -0.4011318   0.90454163
  0.25672426  0.4882590

track_id =1000123633
[0.20369562 0.94960209]
track_id =1000123649
[ 0.1407825   0.397464    0.13227937 -0.20449926  0.16195212 -0.09557632
  0.33685028  0.59359633  0.56497722 -0.34156647  0.96167139  0.68899765
  0.49977415  0.70377709  0.95936838 -0.02073098 -0.16129395  0.25706878
 -0.18142016  0.8792644   0.88580981  0.96415288  0.38609838  0.87366296
  0.63976319  0.98249099  0.89693717  0.02042855  0.99827811 -0.3960698
 -0.78221271  0.6131154  -0.67402305 -0.81559783  0.93911218  0.94061124
  0.92749934  0.12491276 -0.11271518  0.63341247  0.54717468  0.9448617
  0.98680156  0.8631393  -0.9147318   0.83517098  0.30644314 -0.02471082
 -0.88639116  0.88305054  0.89001647  0.42905725  0.36705909]
track_id =1000123665
[ 0.94639133  0.97780506  0.95510226  0.98966112  0.96220595  0.84907441
  0.86266582  0.41747379 -0.08340317  0.9509806   0.673313    0.49450742
  0.9800482   0.93202163  0.3677822   0.93999625 -0.51678778 -0.89616319
 -0.74045185  0.00643299  0.82919865  0.50652933  

track_id =1000125002
[0.9107022]
track_id =1000125009
[-0.35755775  0.03261592  0.04607181 -0.8503608  -0.85357717  0.53297655
  0.81922384 -0.43973169 -0.03584642  0.82246553  0.61292482 -0.8986417
  0.81916771 -0.41045269  0.28683087  0.96022437  0.89637272  0.94577314
  0.84086007  0.77391637 -0.1472669   0.8856108 ]
track_id =1000125032
track_id =1000125063
[-0.89429573 -0.71400696  0.7860147   0.98872018  0.34813603  0.35375016
 -0.54916725  0.31276402 -0.35455294  0.93795346  0.68798434 -0.0542787
  0.39593122  0.09475536  0.87289694 -0.72107192 -0.94223546 -0.95462646
  0.78243663  0.96613724  0.97380282 -0.91853074  0.93277527  0.56331804
  0.67808053 -0.98215947  0.27397705  0.59607651  0.86709252  0.67105212
  0.79085485 -0.36714828 -0.17300098  0.69086707  0.14500259  0.22616302
 -0.63964452  0.95478479 -0.18577945  0.12878103 -0.9793219   0.33432065]
track_id =1000125067
[ 0.42488166  0.64890678 -0.8721943   0.95854646 -0.81288284 -0.56559417
 -0.51640076  0.92659696 -0.186

[-0.87484773  0.5635364  -0.75841437  0.9768893   0.52101872]
track_id =1000126191
[-0.55943762  0.58688876  0.65610644  0.93866664  0.48304769]
track_id =1000126238
[ 0.97779109  0.60348541 -0.94281791  0.03392892  0.54091946 -0.40138494
 -0.99183479 -0.02588025  0.64168375  0.97603692]
track_id =1000126252
[ 0.73747712 -0.17418951  0.99700357 -0.0267874  -0.22747129  0.45724147
  0.46980072  0.2465405  -0.29940615 -0.20702353  0.19896293  0.22394397
 -0.56305372 -0.93019911 -0.79296851  0.87834626 -0.03674479  0.84431075
  0.55034338  0.8829364   0.57310471 -0.85520905 -0.14003788  0.94440608
 -0.62395394 -0.46072423  0.84432825  0.356704   -0.12925551  0.18740856
  0.47926803 -0.89563606]
track_id =1000126320
[ 0.90161923  0.11136168  0.96828007 -0.54128123 -0.58633676  0.78839067
  0.02751735  0.93050982  0.41009856  0.90153442 -0.65296406 -0.57292987
 -0.85244235  0.91860249  0.5569691   0.97688914]
track_id =1000126322
[ 0.22231616 -0.52317977  0.01966914  0.48783491  0.72995507 

[0.87429558 0.24303079]
track_id =1000126938
[-0.02326944 -0.0840087   0.42819044 -0.38298519  0.66387866  0.80864757
 -0.01116833 -0.96386219  0.22394203  0.81778808  0.3218264   0.22154369
  0.74598748 -0.53212902 -0.87573388  0.21498095  0.93432533 -0.99086963
  0.88066361 -0.65391185  0.6978415  -0.87714379  0.61276737  0.85094533
  0.44346628  0.44434989  0.67039557]
track_id =1000126959
[-0.97206388  0.17403896  0.81712513  0.2729446  -0.01048499 -0.52299343
 -0.55041943 -0.92925028 -0.81060384  0.45077615]
track_id =1000126961
[ 0.65039601 -0.1806371  -0.79615743 -0.9308493  -0.54980381  0.24978105
  0.95653958  0.75670784  0.66967366  0.66068004  0.10488458]
track_id =1000126996
track_id =1000127008
[-0.59289068  0.46321061  0.50979903 -0.1323833   0.80285638 -0.61883509
  0.5747428  -0.1152058   0.77020334  0.85494292 -0.6337259  -0.60504192
 -0.21121573 -0.52613364  0.97460274  0.93808892  0.59467219 -0.80511653
  0.70314229  0.9192208   0.14745619  0.92765159 -0.74067509 -0.

track_id =1000128441
[-0.05648419 -0.96733985 -0.54740817  0.9605927   0.87905368  0.23485303
  0.89403097  0.67169951]
track_id =1000128450
track_id =1000128475
[0.48847785 0.67829452 0.13180445 0.27438554 0.75926977 0.61423484
 0.73521014]
track_id =1000128491
[-0.7458182   0.49072007  0.62698005  0.93478907  0.70498956 -0.248647  ]
track_id =1000128511
[-0.63632925  0.29490269  0.81741079  0.56592203]
track_id =1000128518
[ 0.93796005  0.00930372  0.37558086  0.95569665 -0.65156918]
track_id =1000128522
[ 0.80309336 -0.03025205  0.59596385  0.98849996  0.44649714  0.55679084]
track_id =1000128541
[ 0.84498421  0.90812916 -0.5376937   0.91246139  0.77885277 -0.68316705
 -0.48612835  0.63478586  0.58004952 -0.73710765  0.48351191 -0.00491111
 -0.72440462 -0.06037079  0.77931125  0.95618662  0.7147869   0.46188319]
track_id =1000128546
track_id =1000128552
[ 0.83173472  0.63858723 -0.88853762 -0.96882397]
track_id =1000128588
[-0.86908659  0.41948443  0.88168119  0.14893046  0.14471875

[-0.35778547  0.49612412  0.93687934 -0.07672098  0.16669746 -0.47911925
  0.47121494 -0.35894572  0.50141894 -0.60067289 -0.25286503  0.77670101
  0.43171917  0.53048977  0.81594384  0.85786557  0.53631081  0.78730954
 -0.9641839  -0.14771317  0.57532949  0.91068249 -0.61966687  0.50626021
  0.85447785  0.3839904   0.26373767 -0.16398872  0.30111041  0.27441654
  0.07804114 -0.86806982 -0.36203115 -0.63563846 -0.16146403  0.70130289
  0.78682329  0.95362335  0.52468239  0.88515944  0.9740443   0.11297462
  0.24409886  0.63754078 -0.35832657  0.75213357 -0.66277967  0.87442306
 -0.41634661  0.54204894  0.98068153  0.00755987  0.19552985  0.28611029
  0.21360965  0.36063409 -0.26957735 -0.1340071   0.79446013  0.41377244
  0.87663675]
track_id =1000129997
[0.98654357 0.94985036 0.98796184 0.782186   0.81102486 0.5624669
 0.6146863  0.78779174 0.99635216 0.81859441 0.86975617 0.92692215
 0.52373414]
track_id =1000130001
[ 0.98055357  0.66131305  0.90303192  0.37492196  0.75755906 -0.9615

track_id =1000131255
[-0.83542042  0.72076479  0.43963744 -0.58121012  0.8599099  -0.73760204
 -0.45971417]
track_id =1000131264
[ 0.7427919   0.82779374  0.69934991 -0.73986708  0.92135245  0.53071402
  0.63830778  0.90852409]
track_id =1000131281
[0.67667726 0.90464824 0.94233219 0.74245324 0.25464238]
track_id =1000131311
[ 0.54341976  0.88309488  0.97303892  0.97950249  0.8526299   0.78606365
  0.97064863 -0.86962553  0.99982116  0.46685011 -0.67617839  0.33402558
 -0.60911846 -0.46673972 -0.78034794 -0.6683809   0.91238995  0.98698417
  0.96318987  0.89593061  0.89807055  0.89372784  0.60463268  0.2726837
  0.92253822  0.92802856  0.31926683  0.9597447   0.463814    0.50218812
  0.90467114  0.91668553  0.9848349   0.85345856  0.62557156  0.85604763
  0.74463025  0.9899944   0.10390803  0.12509867 -0.05273759  0.98933983
  0.96501622  0.98875557  0.97478608  0.94786217  0.83594777  0.70803004
  0.9725423   0.92724051  0.84746884  0.84406149  0.86115295  0.71112354
  0.84059125  0.3

[-0.05172543 -0.01920101  0.80972069  0.97958907  0.72533357  0.99879982]
track_id =1000131878
[0.43469902]
track_id =1000131895
[-0.11319675  0.04313814  0.60809066  0.98743524  0.68916286 -0.51632847
 -0.84739377 -0.09973088  0.96153306 -0.60974644]
track_id =1000131902
[-0.4232013   0.31832235  0.94407127  0.55735504]
track_id =1000131913
[0.3303445]
track_id =1000131934
[0.08046947 0.63385843 0.72779567]
track_id =1000131938
track_id =1000131940
[ 0.97484019  0.95751291  0.97638041 -0.94138385]
track_id =1000131958
[ 0.37436912  0.8136213   0.83379003  0.88060427  0.73596673 -0.93909321]
track_id =1000131985
[-0.16997677  0.95324591  0.89907916  0.16744486  0.89501115  0.66258163
 -0.15632277 -0.56799998 -0.36537236 -0.82489108 -0.22795742 -0.19075882
  0.11594135  0.1762273  -0.83939878 -0.14202322  0.99268936  0.78340444
  0.99578103  0.72310048 -0.71149462 -0.24054423]
track_id =1000132002
track_id =1000132040
[-0.10767619]
track_id =1000132090
[ 0.70307746 -0.93721221 -0.064554

[ 0.36412399 -0.25023258 -0.21087053  0.70946261  0.91293249  0.59686899
  0.98333589  0.96482936  0.94374326  0.14626858  0.8837719   0.9973911
  0.67164518 -0.40318037  0.4399493   0.47247829  0.87672699  0.71901481
  0.69948052  0.998437    0.92004974  0.9845585   0.98410592  0.97399483
  0.99700715  0.85967138  0.96894766  0.66178095  0.18403648  0.06791328
  0.71297823  0.91678302  0.92158109  0.97456503  0.86180303  0.6526002
  0.96950291  0.89331382  0.75387537 -0.49210592  0.263916    0.07005277
  0.73213796  0.95323178  0.66714212  0.97045715  0.62673225  0.42521063
  0.7263656   0.69352031  0.75639561  0.79347932  0.00747646 -0.47827169
 -0.29270377  0.97690336 -0.15682087  0.14610233 -0.37502954  0.77322521
  0.98671565  0.9390214   0.55385276 -0.18495298  0.76132719  0.89854946
  0.53666029  0.55509205  0.52141501  0.07387858 -0.2309486  -0.2405617
 -0.33650304  0.88904575  0.95041055  0.21813389  0.78694182 -0.07575235
 -0.26924185  0.16841536  0.71593046  0.94834327  0.98

[ 0.55638227 -0.66784319 -0.36631999  0.44365987  0.52081074  0.85002126
 -0.88845272  0.15679522  0.81415681  0.99659908  0.78825227  0.74206771
  0.95935614  0.90373104 -0.59340873  0.06935159  0.45766142  0.34217237
  0.66861849  0.18538855  0.66991169  0.87007087]
track_id =1000133853
[-0.99417814  0.78659136 -0.99446311  0.33449994  0.98680251  0.33088133
  0.09814444  0.46451697  0.69343571 -0.04027581 -0.22867441  0.09932267
  0.49389857  0.52587513 -0.9819712  -0.80521349  0.19479233 -0.1898621
  0.92769086  0.68342668  0.22395702  0.78625588  0.96913555  0.77641763
  0.97322069  0.19163907  0.58156568 -0.82366592  0.70905979]
track_id =1000133878
[ 0.52015502  0.9811964   0.77765369 -0.53526581]
track_id =1000133889
track_id =1000133893
[ 0.54447037 -0.63285401  0.47396371 -0.556831    0.04604297  0.26070853
  0.98903235  0.98892222  0.64294219  0.1095729   0.93477608  0.90594276
  0.96998813  0.5723039   0.5651022   0.00604598  0.05596943  0.62891016
 -0.88190869 -0.97848409 

[ 0.47324022 -0.63678287 -0.57053754  0.82445835 -0.6074706  -0.78962342
 -0.61335767 -0.59008546  0.63351136]
track_id =1000135021
[ 0.84244294  0.894559    0.95718096 -0.19297629  0.10749995  0.30155196
  0.09693513 -0.75909044  0.81749712  0.74338603 -0.84294047  0.99180026
  0.06054897  0.03514961  0.62796094  0.05574566  0.06650771  0.77693803
 -0.00281935  0.49166967 -0.46311731 -0.5360409   0.27060489 -0.21952854
 -0.60396712  0.54794833  0.87122723  0.28154067  0.45985182  0.15120763
 -0.68718062  0.90467577  0.48219464 -0.90276294  0.1471403   0.57361337
  0.03647858 -0.17353367 -0.51319918  0.82944787  0.76026524  0.86975293
  0.94655408  0.78075265  0.98292818 -0.01714007  0.86088704 -0.63180833
 -0.84303156 -0.50021956 -0.12087123  0.42336398 -0.85930967  0.59859195
 -0.6573507   0.46319298  0.77696017  0.99329595  0.80321994  0.44199718
 -0.97142903  0.21111379  0.25790273 -0.17064387  0.83213391  0.58904628
 -0.31816467 -0.63569809 -0.2521412   0.18021934  0.88466828]
tra

[ 0.96742293  0.99473839  0.40990448 -0.88800209 -0.77720327 -0.90428475
  0.89733685  0.39665476  0.65695337 -0.32132693  0.92629684 -0.64120408
 -0.29636195  0.09868966 -0.21471805  0.62724004  0.99559017  0.84099622
  0.98731734 -0.1708762  -0.55328119 -0.4823175   0.33432353 -0.64230416
  0.93797918  0.66113175 -0.30866773 -0.00288285  0.61188077  0.92839852
  0.65773954 -0.87922827 -0.30243661 -0.03782519 -0.25691162]
track_id =1000135523
[-0.78599287  0.52008169 -0.67094039 -0.97094278  0.22645519  0.04212227
 -0.54844026  0.91309449 -0.42465793  0.44848747 -0.62102605  0.52441389
  0.70518088 -0.19496266  0.71856054]
track_id =1000135524
[-0.35481296  0.16466677  0.2425107  -0.03239444  0.58281821  0.5077797
  0.45157096 -0.41505648  0.8384631   0.35699467  0.79097859 -0.31481969
  0.59461243 -0.64023629  0.85423863]
track_id =1000135576
[ 0.07582899  0.23750751 -0.29816673  0.50844891  0.40797831  0.28001412
  0.49063913  0.87087409 -0.62629982  0.89252536  0.68270639 -0.876914

track_id =1000136890
[0.25432673]
track_id =1000136940
[ 0.76057973  0.955617    0.97936491  0.28082118 -0.97261741  0.65870302
 -0.17605475  0.09186571 -0.12875864]
track_id =1000136941
[0.57938559 0.29731746 0.25276481 0.67919003]
track_id =1000136991
[ 0.69732698  0.81906638  0.65692436 -0.49296921  0.84516322  0.75527923
  0.98142233 -0.64550234 -0.08759659 -0.94325123 -0.41350629 -0.4970897
 -0.53399743 -0.65719796 -0.40006018  0.84080415  0.5687195   0.49791354
  0.91730159 -0.42118273  0.81880419  0.47135076  0.98050823]
track_id =1000136998
track_id =1000137007
[ 0.01905553 -0.70990556 -0.98444943]
track_id =1000137008
[ 0.70755816  0.0165941   0.95653851  0.81905861  0.75588548  0.38839297
  0.44366587 -0.80105247  0.76407471]
track_id =1000137021
[-2.61877333e-01  5.06530654e-01  3.98490925e-01  4.84680452e-01
 -7.83909639e-01  1.39285383e-02  7.50088062e-02  9.82550690e-01
 -7.02167595e-01  2.37092068e-01  7.76020289e-01 -8.45743093e-01
  6.87862657e-01 -8.03868436e-01  9.54

track_id =1000138242
[ 0.89708135  0.56195242 -0.62795259 -0.92162329 -0.58771415 -0.30077625
 -0.13819889  0.95459291 -0.02771275 -0.89905343  0.94707051  0.99405008
  0.12550731  0.34875085  0.83301462  0.06729601  0.87501847  0.02957753
  0.32844871  0.78469999  0.83689787 -0.29950026  0.6345444   0.78838269
 -0.22283774 -0.74106123  0.48035712  0.61991624  0.97669821  0.80843144
  0.53743242  0.85553609 -0.3916577   0.7655161  -0.40969868  0.05878198
 -0.95545278  0.68090486 -0.28822039  0.91749884  0.84835066  0.3188334
 -0.56775093  0.38002504  0.91739941 -0.63889251 -0.68344186  0.43047501
  0.88944379 -0.34778912 -0.86540353 -0.96413025  0.66406873  0.0531414
  0.71756746  0.96275858  0.91256498 -0.23541672  0.48913023  0.26603526
 -0.79452137  0.23890711  0.0400858  -0.30303102  0.87795534  0.63351067
  0.38066617  0.94771875  0.22437635  0.39865067  0.87296449]
track_id =1000138249
[-0.42606007]
track_id =1000138251
[ 0.52766303 -0.76698914  0.65479787  0.07226211  0.62936838

[ 0.51416614  0.86130684 -0.70841443  0.56846507  0.30784886  0.95773254
 -0.35447613 -0.25832146  0.99914386 -0.28028822  0.9775347   0.85000861
  0.86206241  0.95832873  0.99841411 -0.88916832 -0.38899636  0.79500185
  0.11379119  0.6006885   0.9988396   0.92240467  0.99910537 -0.67277178
 -0.39053182  0.05543739  0.97188917  0.95977969  0.23097518  0.05094368
  0.98884745  0.91523978  0.6594993   0.73651466  0.83909512  0.89056925
  0.89196694  0.96379485  0.74457328  0.94747954  0.89312773  0.94996921
  0.64108294]
track_id =1000139567
[ 0.00441965  0.57244127  0.53542408 -0.85281091  0.46617673]
track_id =1000139606
[0.71807077 0.70165171]
track_id =1000139607
[ 0.76050033  0.51309778  0.33964457  0.72856093  0.84489695 -0.84380227
  0.86332989  0.50202913 -0.37733431 -0.01819478  0.47408772  0.89733723
  0.94237454  0.74929277  0.81544478  0.95649737]
track_id =1000139614
[0.94776278 0.99298729 0.99944188 0.92052202 0.82703387 0.91257443
 0.65229887 0.93981306 0.80492442 0.880264

track_id =1000140277
[ 0.97389477  0.85492376  0.15197093 -0.92213772  0.60945387 -0.02186972
  0.26547775  0.41336451  0.80244231  0.90964331 -0.01317187  0.8729355
 -0.90308582  0.88250533  0.93701226  0.5245689  -0.23038644  0.42813187
 -0.3373958   0.90600952  0.85346609 -0.1789995   0.16907976  0.79392544
  0.89542577]
track_id =1000140300
track_id =1000140335
[ 0.66806172 -0.33960628  0.90287136  0.98544616]
track_id =1000140346
[ 0.41731256  0.54362899 -0.63183755  0.92584984  0.90248988 -0.02439388
  0.83154537  0.76215167  0.38054481  0.26557374  0.24558916 -0.98811817
 -0.61133022  0.85472667  0.29434877  0.43051525  0.31199147  0.76032419
  0.20944673  0.90018843 -0.41814197 -0.88720784 -0.77843791 -0.20534672
  0.80463737  0.72022822 -0.1722466   0.8129089   0.85155716 -0.75331534
 -0.84672769 -0.07834109  0.63686567  0.86323477  0.43502883  0.47309983
  0.81244059  0.97576362  0.67562534]
track_id =1000140349
[ 0.9947617  -0.17048546 -0.77249674  0.56600568  0.90661603  0.

[-0.96912462  0.93279386]
track_id =1000141050
[ 0.79029588  0.76856471 -0.89815344  0.5727862   0.15173013  0.47498142
 -0.09833178 -0.58338649]
track_id =1000141067
[ 0.2981901  -0.51807699  0.0782967   0.87739164  0.91934729  0.86350786
  0.83084155  0.76819887  0.1112978   0.99740442 -0.37477754  0.98928636
  0.88275794  0.69899397 -0.89192948  0.8053791  -0.30096878  0.80883921
  0.975147  ]
track_id =1000141095
[0.38884601 0.30337704]
track_id =1000141128
[-0.47229833  0.31043365 -0.59017878 -0.89258538 -0.4299514  -0.223701
 -0.42578294  0.26868211  0.63474513 -0.05963089  0.71161103  0.33347454
  0.21679323  0.8542847   0.92827803 -0.93019925  0.60226875  0.87192885
  0.63778706  0.99175292  0.66877172 -0.00247649 -0.34305557 -0.70775971
  0.96897847 -0.21432575  0.76477709  0.02379882 -0.40133407  0.64091971
  0.70804687  0.46544948  0.82804315 -0.61494984  0.85420501  0.96470233
  0.96721769  0.97438334  0.41954339  0.0766924  -0.58167615 -0.61455005
 -0.89867475  0.39980185 

[ 0.33649202 -0.42045928  0.52457883 -0.25976818 -0.00401798 -0.66705745
 -0.5165966 ]
track_id =1000141631
[ 0.29953597  0.1975601  -0.5232625   0.46049487  0.90751555 -0.172309  ]
track_id =1000141643
[0.62745898 0.72402705 0.47592725 0.20122771 0.83097928 0.90350529]
track_id =1000141678
[-0.49891793  0.58647939  0.64249322 -0.79865452  0.7354553  -0.6034168
 -0.10672938 -0.91573291 -0.27317801  0.78064409  0.78086285  0.9885308
 -0.78410263 -0.94028777  0.92161623 -0.64204763 -0.88386531]
track_id =1000141696
[ 0.15520272 -0.33311351 -0.52006211 -0.54006837 -0.2949955  -0.67050083
  0.20551007  0.2812502  -0.32492753 -0.08185607 -0.76376204  0.73993084
  0.72971314 -0.64821635 -0.42203472  0.99035662  0.95951873  0.71047788
  0.4972852 ]
track_id =1000141724
[-0.15886524 -0.46649607]
track_id =1000141755
track_id =1000141756
[-0.96243057  0.89138323  0.71485789  0.75368069 -0.61912843 -0.62658204
  0.85814508  0.83144251  0.55541092  0.74485991  0.8935861   0.9542854
  0.92861471  

track_id =1000142925
[ 0.90921348  0.8066338   0.89674037  0.97176453  0.95486324 -0.16540112
 -0.0229691  -0.07699487  0.30087574  0.74681777  0.88875961  0.99057539
  0.40655221]
track_id =1000142946
[ 0.61337381  0.12940154  0.79849434 -0.20868538  0.22107063  0.60005861
  0.71031787  0.59133164  0.67561912  0.61211218  0.54288064  0.71093845
 -0.01196269]
track_id =1000142987
[ 0.37500028 -0.73256354 -0.14095276 -0.43442121 -0.79826005  0.54688531
 -0.99404866  0.90681662  0.80392151  0.9592542  -0.91870015 -0.3638885
 -0.60722017 -0.43513252  0.21431981 -0.9200907   0.77853785  0.90030205
 -0.85458777  0.37604097]
track_id =1000142999
[ 0.92451799 -0.02181751  0.71238787 -0.1251937   0.88956196  0.7727731
  0.66959029  0.99929637  0.9022452   0.85808594  0.65425271  0.88483619
  0.99174411  0.49490552]
track_id =1000143002
[0.56886964]
track_id =1000143019
track_id =1000143031
[-0.86555746  0.81466366  0.88864449 -0.68722696  0.96756578  0.42703859
 -0.47044277 -0.73235456 -0.2834

track_id =1000144561
track_id =1000144566
[-0.46232232  0.75100059  0.46574988 -0.34598765 -0.09800926 -0.23444866
 -0.80184196  0.38748152  0.138738    0.99672239  0.93286414  0.84960059
 -0.72200255  0.92538456  0.12123915  0.26802551  0.3480502  -0.02350508
  0.96008788  0.812499   -0.71266318 -0.59293676]
track_id =1000144571
[ 0.90624615 -0.10460732  0.4411288   0.43501575  0.68664159  0.85240193
  0.51108831  0.70605031  0.99914885  0.29642386  0.96369512  0.77919587
  0.74857236  0.57147456  0.98038915  0.83233081  0.41392153 -0.61852596
  0.21437989  0.09356191  0.99900069  0.88806649  0.91051449  0.99677652
  0.86729162  0.84554854  0.74337064  0.98549957  0.83028659  0.98507525
 -0.47468447  0.73133434  0.67235384 -0.65678892  0.9957592   0.98079442
 -0.16121772 -0.40073546  0.55832918 -0.4550342  -0.49628617  0.90704961
 -0.4644941   0.96566852  0.52564295 -0.92051729  0.40675424  0.61519629
  0.96894847  0.53448056  0.6601869   0.58625171 -0.65711763 -0.56710775
 -0.9288368

track_id =1000145040
[-0.79926067 -0.46872543  0.68503941 -0.82882478]
track_id =1000145070
[ 0.16216621  0.90793982  0.66026657 -0.01827765 -0.27735743  0.32925611
 -0.82877902  0.75850526  0.93660207  0.60794385 -0.9286308 ]
track_id =1000145105
[0.95712424 0.86201336 0.93884831 0.92380084 0.82812702 0.95128577
 0.94611092 0.74884414 0.84018482 0.96128138 0.92017136 0.95018612
 0.50709296 0.98066018 0.50331046 0.92753598 0.63539812 0.80804096
 0.94596863 0.95095246 0.93164942]
track_id =1000145107
[0.99575764 0.98717568 0.9207095  0.54729273 0.67143712 0.92609867
 0.98316457 0.70075056 0.92645569 0.97781622 0.16983961 0.3415524
 0.54598825 0.76030801 0.23076869 0.76412458 0.94910751 0.90965171
 0.71275038 0.13869094]
track_id =1000145122
[ 0.59672425 -0.87443665  0.19648912  0.96884478 -0.16635131 -0.70260894
 -0.19608417  0.51351724 -0.58963765 -0.7476436   0.89762731  0.96787808
  0.53102925  0.25012222  0.14428711  0.66639579]
track_id =1000145132
[-0.99998706  0.98144829 -0.40680

[0.91584025 0.96997325 0.45108222 0.85378171 0.92376202 0.92808636
 0.99867668 0.93113639 0.93180721]
track_id =1000146530
track_id =1000146537
[ 0.03638492 -0.95060188  0.98942504  0.97048023  0.56668037  0.45228593
  0.71841368  0.94965515]
track_id =1000146544
track_id =1000146590
[0.72997229 0.76039078 0.99072844 0.50104639 0.6561296 ]
track_id =1000146602
[-0.56050165]
track_id =1000146608
[ 0.96367927  0.94590691  0.90959004  0.5481864  -0.16503972  0.91634841
  0.35754106 -0.87704459  0.93431725  0.95048925 -0.01300297  0.45352156
  0.89392913  0.56581902  0.94786074  0.16965443 -0.42283572  0.98033589
  0.96450658  0.98708154  0.83644774 -0.10039704  0.25008043  0.98320394
  0.99922118  0.08071731  0.79552537  0.29571797  0.42046251  0.99964796
  0.89593719  0.42514936 -0.2277236   0.98159381  0.93943956  0.96190003
  0.92084495  0.99079175 -0.05883065  0.1066317   0.67806397]
track_id =1000146634
[ 0.74975541  0.63088297  0.84856364 -0.10979032]
track_id =1000146638
[-0.284080

[ 0.57971466 -0.26465643  0.7367093   0.7465408 ]
track_id =1000147725
[-0.34113383  0.26220151  0.78053342 -0.49762078  0.21210132  0.63981582
  0.59251073  0.85680713  0.82798533  0.35065164  0.31680054]
track_id =1000147731
[-0.51302159 -0.96057238 -0.07971828 -0.59693075 -0.46551563  0.65305882
  0.12814913  0.79272635 -0.71098396]
track_id =1000147775
[ 0.67908596 -0.02001057  0.78301376  0.87999231  0.88809135  0.85285909
  0.96685206  0.62185978 -0.40550161 -0.01298093  0.87186079 -0.36160679
  0.96759201  0.63255359  0.17443282  0.98171611 -0.39215906 -0.06403199
 -0.6676379  -0.16063571 -0.76986922  0.64395127  0.63733503  0.6777576
  0.75573837  0.28785198 -0.37130641  0.9776663 ]
track_id =1000147778
[ 0.95434945 -0.23100728 -0.27131038 -0.55232403  0.10832281  0.37926121
  0.95217856 -0.68284595 -0.19081298 -0.95282859  0.76182939 -0.44279443]
track_id =1000147804
[0.77814419 0.49905879 0.9518914 ]
track_id =1000147813
[-0.34756183  0.37884415  0.97737356 -0.14125791 -0.448

[ 0.86975392 -0.50467997  0.0615288 ]
track_id =1000148822
[ 0.3936435   0.82047164  0.9983647   0.08192159 -0.18834975  0.99996691
  0.64060848  0.92418971  0.99999743  0.57925617 -0.25946222 -0.05190184
 -0.29156955  0.86559985 -0.95765185 -0.48312745  0.86280143]
track_id =1000148847
[0.9999867  0.88617701 0.96201752 0.95211363 0.9913711  0.93963975
 0.9735428 ]
track_id =1000148859
[0.92767078]
track_id =1000148863
[ 0.70274049  0.87754585  0.24260115 -0.83377466 -0.23408073]
track_id =1000148870
[0.99836059]
track_id =1000148880
[ 0.02591014  0.61234845  0.89810629  0.40944405  0.16014798 -0.8722224
 -0.95674527  0.27351257 -0.42548434  0.28371462  0.61421757  0.99719221
  0.70950627  0.98966261 -0.99516779  0.93331172  0.90229217  0.24565018
 -0.1301482   0.82752102 -0.08770792 -0.8172455   0.94663685 -0.71313901
  0.38297966 -0.08155463  0.95129375  0.77042824  0.9130763   0.92743189
  0.79008697]
track_id =1000148891
[-0.78548147  0.94942113  0.86390099  0.12025998 -0.4050371  

KeyboardInterrupt: 